remote_aliases:
  AliceSpringsMulga: AliceMulga

configs:
  base_path:
    local: /opt/TERN_EP
  stream:
    site_config_files:
      local: site_configs/operational
    site_config_files_legacy:
      local: site_configs/legacy
    secrets:
      local: secrets/logins.yml

raw_data:
  base_path:
    local: /store/Raw_data/<site>
  stream:
    flux_slow:
      local: Flux/Slow
      remote: uqrdm:TERNEP-Q5937/Sites/<site>/Data/Flux/Raw/Slow
    flux_fast:
      local: Flux/Fast
      remote: uqrdm:FLUXARCH23-Q6223/Sites/<site>/Data/Flux/Raw/Fast/TOB3
    flux_fast_aux:
      local: Flux_aux/Fast
      remote: uqrdm:FLUXARCH23-Q6223/Sites/<site>/Data/Flux_aux/Raw/Fast/TOB3
    profile:
      local: Profile
      remote: uqrdm:TERNEP-Q5937/Sites/<site>/Data/Profile/Raw

processed_data:
  base_path:
    local: /store/Processed_data/<site>
  stream:
    profile:
      local: Profile
      remote: uqrdm:TERNEP-Q5937/Sites/<site>/Data/Profile/Processed

homogenised_data:
  base_path:
    local: /store/Homogenised_data
  stream:
    nc:
      local: NetCDF_test
      remote: uqrdm:TERNEP-Q5937/EPCN_Share/Homogenised_data/NetCDF
    toa5:
      local: TOA5_test
      remote: OneDrive_UoM:Documents/RTMC/Site_data
    toa5_legacy:
      local: TOA5

network:
  base_path:
    local: /opt/TERN_EP/network
  stream:
    state:
      local: state
    status:
      local: status
      remote: sftpgo:/web-sites/flux-status-test.tern.org.au/RTMC

logs:
  base_path:
    local: /store/Logs
  stream:
    network_logs:
      local: Network
    site_logs:
      local: Sites/<site>
